name: Build and Release steGO

on:
  push:
    branches:
      - main  # Trigger the release workflow only on the main branch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Initialize Go Modules
        run: go mod tidy

      - name: Build Executable
        run: |
          GOOS=$(go env GOOS) GOARCH=amd64 go build -o steGO_${{ matrix.os }} steGo.go

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: steGO_${{ matrix.os }}
          path: steGO_${{ matrix.os }}

  release:
    needs: build  # Run only after builds complete successfully
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: steGO v1.0.${{ github.run_number }}
          draft: false
          prerelease: false
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

