name: Build steGO Steganography Tool

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Initialize Go Modules
        run: go mod tidy

      - name: Debug - List Files
        run: ls -la  # Check if steGo.go is present

      - name: Build Executable
        run: |
          go build -o steGO_${{ matrix.os }} steGo.go  # Corrected filename

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: steGO_${{ matrix.os }}
          path: steGO_${{ matrix.os }}



