name: Build steGO Steganography Tool

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Updated to latest version

      - name: Setup Go
        uses: actions/setup-go@v4  # Updated to latest version
        with:
          go-version: 1.23.4

      - name: Build Executable
        run: |
          GOOS=$(go env GOOS) GOARCH=amd64 go build -o steGO_${{ matrix.os }} steGO.go

      - name: Upload Binaries
        uses: actions/upload-artifact@v4  # Fixed the deprecated version
        with:
          name: steGO_${{ matrix.os }}
          path: steGO_${{ matrix.os }}

